version: '3.8'

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
        #    ports:
        #      - 9090:9090
    expose:
      - 9090
    networks:
      external:
        ipv4_address: 172.25.2.6
    restart: always

networks:
  external:
    external: true
    name: server_side

volumes:
    prometheus_data: 
