version: '3'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx_reverse_proxy
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "9200:9200"
    networks:
      elastic:
      ipv4_address: 172.25.2.2

    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
    elastic:
      external: true
      name: server_side

