version: '3'

services:
  Edge-server:
    build:
      context: .
    image: bird:ubuntu-20.04
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1 
    restart: unless-stopped
    container_name: edge-server
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      server_side:
        ipv4_address: 172.25.2.1
      bgp_side:
        ipv4_address: 172.25.1.1
    command: sleep 1000000

  ISP-Router:
    image: bird:ubuntu-20.04
    build:
      context: .
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1 
    restart: unless-stopped
    container_name: isp-router
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      bgp_side:
        ipv4_address: 172.25.1.2
      client_side:
        ipv4_address: 172.25.0.1
    command: sleep 1000000


networks:
    server_side:
      external: true
      name: server_side
    bgp_side:
      external: true
      name: bgp_side
    client_side:
      external: true
      name: client_side
