#FROM ubuntu:20.04
FROM ubuntu:22.04
RUN apt update -y
# DEBUG
RUN apt install -y tcpdump 
RUN apt install -y mtr
RUN apt install -y iproute2
RUN apt install -y curl
#RUN apt install -y bird 
RUN apt install -y bird2 
RUN mkdir -p /run/bird/
